{
 "title": "webMethods Microservices Runtime",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    { "expr": "sag_is_uptime_seconds" }
   ]
  },
  {
   "title": "Current Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sag_is_current_stateful_sessions"
    }
   ]
  },
  {
   "title": "Service Instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sag_is_services" }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sag_is_number_nonservice_errors+sag_is_number_service_errors"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sag_is_used_memory_bytes", "legendFormat": "Used Memory" },
    { "expr": "sag_is_max_memory_bytes", "legendFormat": "Max Memory" },
    { "expr": "sag_is_total_memory_bytes", "legendFormat": "Total Memory" }
   ]
  },
  {
   "title": "Top Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sag_is_service_number_access) > 5"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sag_is_http_requests", "legendFormat": "Current Requests" },
    { "expr": "sag_is_total_http_requests", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sag_is_system_threads", "legendFormat": "System Threads" },
    { "expr": "sag_is_service_threads", "legendFormat": "Service Threads" },
    { "expr": "sag_is_max_system_threads", "legendFormat": "Max System Threads" },
    { "expr": "sag_is_peak_service_threads", "legendFormat": "Peak Service Threads" }
   ]
  }
 ]
}